### ISSUE TITLE
Orbit 13659 tar size is 0. It also causes the BW job aborted

### ISSUE THREAD

**Issue by kyang2014** [TerraFusion/basicFusion#301]
Size of 13659archive.tar is 0. at BW, check

ls -ltr /u/sciteam/ymuqun/scratch/bf_workflow/tar/2002/13659archive.tar
-rw-r----- 1 ymuqun ILL_bage 0 Feb 11 20:37 /u/sciteam/ymuqun/scratch/bf_workflow/tar/2002/13659archive.tar

This also causes the BW jobs aborted.
Check /mnt/c/scratch/sciteam/ymuqun/bf-test-all/basicFusion/util/TerraG
en/BF_jobFiles/run11/logs/process/process_11782_14781.log
It states:

Rank 37 [Mon Feb 12 05:12:14 2018] [c21-10c0s6n1] application called MPI_Abort(MPI_COMM_WORLD, 0) - process 37
12-02-2018:05:12:13 ERROR    MPI_Rank 37 [pull_process.py:141] Failed to untar /u/sciteam/ymuqun/scratch/bf_workflow/tar/2002/13659archive.tar
Traceback (most recent call last):
  File "/mnt/c/scratch/sciteam/ymuqun/bf-test-all/basicFusion/util/TerraGen/pull_process.py", line 130, in mpi_rank_untar
    tar = tarfile.TarFile( data.destTarPath )
  File "/mnt/bwpy/single/usr/lib/python2.7/tarfile.py", line 1587, in __init__
    self.firstmember = self.next()
  File "/mnt/bwpy/single/usr/lib/python2.7/tarfile.py", line 2373, in next
    raise ReadError("empty file")
ReadError: empty file
12-02-2018:05:12:14 ERROR    MPI_Rank 37 [pull_process.py:935] Encountered exception.
Traceback (most recent call last):
  File "/mnt/c/scratch/sciteam/ymuqun/bf-test-all/basicFusion/util/TerraGen/pull_process.py", line 931, in <module>
    main()
  File "/mnt/c/scratch/sciteam/ymuqun/bf-test-all/basicFusion/util/TerraGen/pull_process.py", line 815, in main
    worker()                            #
  File "/mnt/c/scratch/sciteam/ymuqun/bf-test-all/basicFusion/util/TerraGen/pull_process.py", line 307, in worker
    func( data )
  File "/mnt/c/scratch/sciteam/ymuqun/bf-test-all/basicFusion/util/TerraGen/pull_process.py", line 130, in mpi_rank_untar
    tar = tarfile.TarFile( data.destTarPath )
  File "/mnt/bwpy/single/usr/lib/python2.7/tarfile.py", line 1587, in __init__
    self.firstmember = self.next()
  File "/mnt/bwpy/single/usr/lib/python2.7/tarfile.py", line 2373, in next
    raise ReadError("empty file")
ReadError: empty file
At last,
_pmiu_daemon(SIGCHLD): [NID 15603] [c21-10c0s6n1] [Mon Feb 12 05:12:20 2018] PE RANK 37 exit signal Aborted
[NID 15603] 2018-02-12 05:12:20 Apid 65060347: initiated application termination
Application 65060347 exit codes: 134
Application 65060347 exit signals: Killed
Application 65060347 resources: utime ~302s, stime ~1229s, Rss ~58012, inblocks ~398643678, outblocks ~386143552

**Comment by LandonTClipp** [comment]
The tar file is in fact 0 size on Nearline: `/projects/sciteam/bage/PerOrbitArchive/2002/13659archive.tar 0GB`

Dr. Yang, if you want to add this orbit to the list of orbits we need to handle manually, that would be good. Maybe also put this list on the Github wiki.

I will begin writing the exception handler for 0 tar sizes now.

**Comment by kyang2014** [comment]
Yes, we will do. Do we have all the input granules at the nearline for this orbit?
Have you finished the comparsion of file size/input file list scripts? If not, I treat those a higher priority than this. Please finish that first.

Kent

**Comment by LandonTClipp** [comment]
File size script has been written, I am running tests on it now and ironing out bugs. I hope my last run is today... script takes a long time to run. I will finish input file list script today or tomorrow. I am beginning now.

**Comment by kyang2014** [comment]
Great, Thanks,
Kent
